# Generated by Django 3.1.7 on 2021-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='types',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('address', 'address')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
