# Generated by Django 3.1.7 on 2021-03-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0006_contact_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='rests.branch'),
            preserve_default=False,
        ),
    ]
