# Generated by Django 3.1.7 on 2021-03-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0009_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_sum',
        ),
    ]
