# Generated by Django 3.1.7 on 2021-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0010_auto_20210310_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='abbr',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
