# Generated by Django 3.1.7 on 2021-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0011_book_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
