# Generated by Django 3.1.7 on 2021-03-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rests', '0012_book_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
